---
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mysterydb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/New_York
      - MYSQL_DATABASE=mystery
      - MYSQL_USER=ops
      - MYSQL_PASSWORD=
    volumes:
      - ./data:/config
    ports:
      - 3306:3306
    restart: unless-stopped

networks:
  default:
    external:
      name: primary
