version: "2"
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./MysteryNightOut:/config/www
    labels:
      - traefik.enable=true
      - traefik.http.routers.mystery.rule=Host(`HOSTNAME_HERE`)
      - traefik.http.routers.mystery.tls=true 
      - traefik.http.routers.mystery.tls.certresolver=lets-encrypt
      - traefik.http.routers.mystery.entrypoints=websecure      
    restart: always
  
  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
     --providers.docker=true
     --providers.docker.exposedbydefault=false
     --entrypoints.web.address=":80"
     --entrypoints.websecure.address=":443"
     --entrypoints.web.http.redirections.entryPoint.to=websecure
     --entrypoints.web.http.redirections.entryPoint.scheme=https
     --certificatesresolvers.lets-encrypt.acme.httpchallenge=true
     --certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web
     --certificatesresolvers.lets-encrypt.acme.caserver="https://acme-v02.api.letsencrypt.org/directory"
     --certificatesresolvers.lets-encrypt.acme.email="EMAIL_HERE"
     --certificatesresolvers.lets-encrypt.acme.storage="/letsencrypt/acme.json"
    container_name: traefik
    restart: always

networks:
  default:
    external:
      name: primary